DROP TABLE IF EXISTS TBL_LEAVES;

CREATE TABLE leaves (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  emp VARCHAR(50) NOT NULL,
  from_date DATE NOT NULL,
  to_date DATE NOT NULL,
  reason VARCHAR(250) NOT NULL,
  status INT(2)
);